/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package essaiemployes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import DAO.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Clarence
 */
public class Clients extends javax.swing.JInternalFrame {
    Connection con;
    PreparedStatement st;
    ResultSet res;    
    public Clients() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajout = new javax.swing.JButton();
        supp = new javax.swing.JButton();
        editer = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        informations = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        nomclient = new javax.swing.JLabel();
        nomtxt = new javax.swing.JTextField();
        prenom = new javax.swing.JLabel();
        prenomtxt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion clients");

        ajout.setBackground(new java.awt.Color(255, 153, 0));
        ajout.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        ajout.setForeground(new java.awt.Color(255, 255, 255));
        ajout.setText("Ajouter");
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });

        supp.setBackground(new java.awt.Color(255, 0, 0));
        supp.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        supp.setForeground(new java.awt.Color(255, 255, 255));
        supp.setText("Supprimer");
        supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppActionPerformed(evt);
            }
        });

        editer.setBackground(new java.awt.Color(0, 204, 51));
        editer.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        editer.setForeground(new java.awt.Color(255, 255, 255));
        editer.setText("Editer");
        editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editerActionPerformed(evt);
            }
        });

        actualiser.setBackground(new java.awt.Color(0, 153, 153));
        actualiser.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        actualiser.setForeground(new java.awt.Color(255, 255, 255));
        actualiser.setText("Actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });

        informations.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        informations.setForeground(new java.awt.Color(0, 153, 255));
        informations.setText("Informations clients");

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setText("ID");

        idtxt.setBackground(new java.awt.Color(204, 204, 204));

        nomclient.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nomclient.setText("Nom");

        nomtxt.setBackground(new java.awt.Color(204, 204, 204));

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        prenom.setText("Prénom");

        prenomtxt.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualiser)
                            .addComponent(editer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nomclient)
                            .addGap(39, 39, 39)
                            .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(informations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(idtxt)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prenom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informations)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomclient))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenom)
                    .addComponent(prenomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajout)
                    .addComponent(editer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supp))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualiserActionPerformed

    private void editerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editerActionPerformed

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
   
        try{
             String DBurl = "jdbc:mysql://projetjava2022.mysql.database.azure.com:3306/booking";
             con = DriverManager.getConnection(DBurl, "remyjova@projetjava2022", "Remy9999.");
             String sql = "insert into clients(idMembres,Nom,Prénom) values (?,?,?)";
             st=con.prepareStatement(sql);
             st.setString(1, idtxt.getText());
             st.setString(2,nomtxt.getText());
             st.setString(3, prenomtxt.getText());
             st.execute();
             con.close();
             JOptionPane.showMessageDialog(null,"Ajout effectué");
                    } catch(Exception e){
                          e.printStackTrace();
                   }

    }//GEN-LAST:event_ajoutActionPerformed

    private void suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JButton ajout;
    private javax.swing.JButton editer;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel informations;
    private javax.swing.JLabel nomclient;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JLabel prenom;
    private javax.swing.JTextField prenomtxt;
    private javax.swing.JButton supp;
    // End of variables declaration//GEN-END:variables
}
