/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package essaiemployes;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import DAO.*;

/**
 *
 * @author Clarence
 */
public class Employes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employes
     */
    public Employes() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backg = new javax.swing.JPanel();
        infos = new javax.swing.JLabel();
        ground = new javax.swing.JPanel();
        ref = new javax.swing.JLabel();
        reftxt = new javax.swing.JTextField();
        namemploye = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        premployes = new javax.swing.JLabel();
        surnametxt = new javax.swing.JTextField();
        departement = new javax.swing.JLabel();
        depttxt = new javax.swing.JTextField();
        compagnie = new javax.swing.JLabel();
        compatxt = new javax.swing.JTextField();
        executer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        backg.setBackground(new java.awt.Color(0, 0, 0));

        infos.setBackground(new java.awt.Color(255, 255, 255));
        infos.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        infos.setForeground(new java.awt.Color(255, 255, 255));
        infos.setText("Informations");

        ground.setBackground(new java.awt.Color(0, 204, 204));

        ref.setBackground(new java.awt.Color(255, 255, 255));
        ref.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ref.setForeground(new java.awt.Color(255, 255, 255));
        ref.setText("Référence");

        namemploye.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namemploye.setForeground(new java.awt.Color(255, 255, 255));
        namemploye.setText("Nom");

        premployes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        premployes.setForeground(new java.awt.Color(255, 255, 255));
        premployes.setText("Prénom");

        surnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnametxtActionPerformed(evt);
            }
        });

        departement.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        departement.setForeground(new java.awt.Color(255, 255, 255));
        departement.setText("Département");

        depttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depttxtActionPerformed(evt);
            }
        });

        compagnie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        compagnie.setForeground(new java.awt.Color(255, 255, 255));
        compagnie.setText("Compagnie");

        executer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        executer.setForeground(new java.awt.Color(204, 204, 0));
        executer.setText("Exécuter");
        executer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groundLayout = new javax.swing.GroupLayout(ground);
        ground.setLayout(groundLayout);
        groundLayout.setHorizontalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundLayout.createSequentialGroup()
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(executer))
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(groundLayout.createSequentialGroup()
                                .addComponent(compagnie)
                                .addGap(42, 42, 42)
                                .addComponent(compatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(groundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(groundLayout.createSequentialGroup()
                                        .addComponent(ref)
                                        .addGap(39, 39, 39)
                                        .addComponent(reftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(groundLayout.createSequentialGroup()
                                        .addComponent(namemploye, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(groundLayout.createSequentialGroup()
                                        .addComponent(premployes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(groundLayout.createSequentialGroup()
                                        .addComponent(departement)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(depttxt)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        groundLayout.setVerticalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ref))
                .addGap(18, 18, 18)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namemploye)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premployes)
                    .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departement)
                    .addComponent(depttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compagnie)
                    .addComponent(compatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(executer)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgLayout = new javax.swing.GroupLayout(backg);
        backg.setLayout(backgLayout);
        backgLayout.setHorizontalGroup(
            backgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgLayout.createSequentialGroup()
                .addGroup(backgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(infos)
                        .addGap(0, 153, Short.MAX_VALUE))
                    .addGroup(backgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgLayout.setVerticalGroup(
            backgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(infos)
                .addGap(36, 36, 36)
                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depttxtActionPerformed

    private void executerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_executerActionPerformed

    private void surnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnametxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backg;
    private javax.swing.JLabel compagnie;
    private javax.swing.JTextField compatxt;
    private javax.swing.JLabel departement;
    private javax.swing.JTextField depttxt;
    private javax.swing.JButton executer;
    private javax.swing.JPanel ground;
    private javax.swing.JLabel infos;
    private javax.swing.JLabel namemploye;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel premployes;
    private javax.swing.JLabel ref;
    private javax.swing.JTextField reftxt;
    private javax.swing.JTextField surnametxt;
    // End of variables declaration//GEN-END:variables
}
