/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package viewmvc;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import DAO.*;

/**
 *
 * @author Clarence
 */
public class Employes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employes
     */
    public Employes() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backg = new javax.swing.JPanel();
        infos = new javax.swing.JLabel();
        ground = new javax.swing.JPanel();
        ref = new javax.swing.JLabel();
        reftxt = new javax.swing.JTextField();
        namemploye = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        premployes = new javax.swing.JLabel();
        surnametxt = new javax.swing.JTextField();
        departement = new javax.swing.JLabel();
        depttxt = new javax.swing.JTextField();
        compagnie = new javax.swing.JLabel();
        compatxt = new javax.swing.JTextField();
        executer = new javax.swing.JButton();
        suppBouton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des employes");

        backg.setBackground(new java.awt.Color(0, 153, 153));

        infos.setBackground(new java.awt.Color(255, 255, 255));
        infos.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        infos.setForeground(new java.awt.Color(255, 255, 255));
        infos.setText(" Informations employés");

        ground.setBackground(new java.awt.Color(204, 204, 204));

        ref.setBackground(new java.awt.Color(255, 255, 255));
        ref.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ref.setForeground(new java.awt.Color(255, 255, 255));
        ref.setText("Référence");

        reftxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reftxtActionPerformed(evt);
            }
        });

        namemploye.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        namemploye.setForeground(new java.awt.Color(255, 255, 255));
        namemploye.setText("Nom");

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        premployes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        premployes.setForeground(new java.awt.Color(255, 255, 255));
        premployes.setText("Prénom");

        surnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnametxtActionPerformed(evt);
            }
        });

        departement.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        departement.setForeground(new java.awt.Color(255, 255, 255));
        departement.setText("Département");

        depttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depttxtActionPerformed(evt);
            }
        });

        compagnie.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        compagnie.setForeground(new java.awt.Color(255, 255, 255));
        compagnie.setText("Compagnie");

        compatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compatxtActionPerformed(evt);
            }
        });

        executer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        executer.setForeground(new java.awt.Color(0, 153, 153));
        executer.setText("Exécuter");
        executer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executerActionPerformed(evt);
            }
        });

        suppBouton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        suppBouton.setForeground(new java.awt.Color(153, 0, 51));
        suppBouton.setText("Supprimer");

        javax.swing.GroupLayout groundLayout = new javax.swing.GroupLayout(ground);
        ground.setLayout(groundLayout);
        groundLayout.setHorizontalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundLayout.createSequentialGroup()
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groundLayout.createSequentialGroup()
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(namemploye, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(premployes))
                                    .addComponent(ref))
                                .addGap(74, 74, 74)
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(surnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                    .addComponent(reftxt)
                                    .addComponent(nametxt)))
                            .addGroup(groundLayout.createSequentialGroup()
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departement)
                                    .addComponent(compagnie))
                                .addGap(18, 18, 18)
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suppBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(depttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                        .addComponent(compatxt))))))
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(executer, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(639, Short.MAX_VALUE))
        );
        groundLayout.setVerticalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reftxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namemploye)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(premployes)
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departement)
                    .addComponent(depttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compagnie)
                    .addComponent(compatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(executer, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(suppBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout backgLayout = new javax.swing.GroupLayout(backg);
        backg.setLayout(backgLayout);
        backgLayout.setHorizontalGroup(
            backgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(infos, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        backgLayout.setVerticalGroup(
            backgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(infos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depttxtActionPerformed

    private void executerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_executerActionPerformed

    private void surnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnametxtActionPerformed

    private void reftxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reftxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reftxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void compatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compatxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backg;
    private javax.swing.JLabel compagnie;
    private javax.swing.JTextField compatxt;
    private javax.swing.JLabel departement;
    private javax.swing.JTextField depttxt;
    private javax.swing.JButton executer;
    private javax.swing.JPanel ground;
    private javax.swing.JLabel infos;
    private javax.swing.JLabel namemploye;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel premployes;
    private javax.swing.JLabel ref;
    private javax.swing.JTextField reftxt;
    private javax.swing.JButton suppBouton;
    private javax.swing.JTextField surnametxt;
    // End of variables declaration//GEN-END:variables
}
