/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package viewmvc;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Clarence
 */
public class Paiementaffichage extends javax.swing.JInternalFrame {

    /**
     * Creates new form Paiement
     */
    public Paiementaffichage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ground = new javax.swing.JPanel();
        nom = new javax.swing.JLabel();
        nomtxt = new javax.swing.JTextField();
        numcarte = new javax.swing.JLabel();
        numtxt = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        crypto = new javax.swing.JLabel();
        cryptotxt = new javax.swing.JTextField();
        payer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Paiement");

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        ground.setForeground(new java.awt.Color(255, 255, 255));

        nom.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        nom.setText("Nom sur la carte");

        nomtxt.setBackground(new java.awt.Color(204, 204, 204));
        nomtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        numcarte.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        numcarte.setText("N° de carte");

        numtxt.setBackground(new java.awt.Color(204, 204, 204));
        numtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numtxtKeyTyped(evt);
            }
        });

        date.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        date.setText("Date d'expiration");

        datetxt.setBackground(new java.awt.Color(204, 204, 204));
        datetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetxtActionPerformed(evt);
            }
        });
        datetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datetxtKeyTyped(evt);
            }
        });

        crypto.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        crypto.setText("Cryptogramme");

        cryptotxt.setBackground(new java.awt.Color(204, 204, 204));
        cryptotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cryptotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cryptotxtActionPerformed(evt);
            }
        });
        cryptotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cryptotxtKeyTyped(evt);
            }
        });

        payer.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        payer.setForeground(new java.awt.Color(255, 51, 51));
        payer.setText("Payer");
        payer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groundLayout = new javax.swing.GroupLayout(ground);
        ground.setLayout(groundLayout);
        groundLayout.setHorizontalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groundLayout.createSequentialGroup()
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(groundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crypto, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cryptotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addGap(115, 115, 115))
            .addGroup(groundLayout.createSequentialGroup()
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numcarte, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom)
                            .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date)))
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(payer, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        groundLayout.setVerticalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(nom)
                .addGap(18, 18, 18)
                .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(numcarte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(numtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(crypto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groundLayout.createSequentialGroup()
                        .addComponent(datetxt)
                        .addGap(35, 35, 35))
                    .addGroup(groundLayout.createSequentialGroup()
                        .addComponent(cryptotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addGap(33, 33, 33)))
                .addComponent(payer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cryptotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cryptotxtActionPerformed
    }//GEN-LAST:event_cryptotxtActionPerformed

    private void datetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetxtActionPerformed

    private void payerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payerActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Paiement effectué !");
        setVisible(false);
    }//GEN-LAST:event_payerActionPerformed

    private void numtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numtxtKeyTyped
        char c = evt.getKeyChar();
             if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) { //VK_BACK_SAPCE = barre d'espace
                  evt.consume();  
             }
    }//GEN-LAST:event_numtxtKeyTyped

    private void datetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datetxtKeyTyped
         char txtpaiement = evt.getKeyChar();
            if ( ((txtpaiement < '0') || (txtpaiement > '9')) && (txtpaiement != KeyEvent.VK_BACK_SPACE)) {
                  evt.consume();  
             }
    }//GEN-LAST:event_datetxtKeyTyped

    private void cryptotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cryptotxtKeyTyped
        char cryptopaiement = evt.getKeyChar(); 
             if (((cryptopaiement<'0')|| (cryptopaiement>'9')&&(cryptopaiement != KeyEvent.VK_BACK_SPACE))){
                         evt.consume();
}
    }//GEN-LAST:event_cryptotxtKeyTyped

    public void run() {
        new Paiementaffichage().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crypto;
    private javax.swing.JTextField cryptotxt;
    private javax.swing.JLabel date;
    private javax.swing.JTextField datetxt;
    private javax.swing.JPanel ground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JLabel numcarte;
    private javax.swing.JTextField numtxt;
    private javax.swing.JButton payer;
    // End of variables declaration//GEN-END:variables
}
