/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package viewmvc;

import java.sql.DriverManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Clarence
 */
public class Statistiques extends javax.swing.JInternalFrame {

    /**
     * Creates new form Statistiques
     */
    public Statistiques() {
        initComponents();

try{
    java.sql.Connection con = null;
String DBurl= "jdbc:mysql://projetjava2022.mysql.database.azure.com:3306/booking";
            // con = DriverManager.getConnection(DBurl, "root", "");
            con = DriverManager.getConnection(DBurl, "remyjova@projetjava2022", "Remy9999.");

            modelmvc.Connection.affiche("DataBase connected !");
String query="Select Nombre de billet, Vol_idVol from réservation";
JDBCCategoryDataset dataset=new JDBCCategoryDataset(con, query);
JFreeChart CategoryDataset;
dataset = null;
JFreeChart chart = ChartFactory.createBarChart("Fréquentation des destinations", "Nombre de billet", "Vol_idVol", dataset, PlotOrientation.VERTICAL, false, true, true);
BarRenderer renderer=null;
CategoryPlot plot=null;
renderer= new BarRenderer();
ChartFrame frame = new ChartFrame("Statistiques", chart);
frame.setVisible(true);
frame.setSize(400,650);

}
catch ( Exception e){
e.printStackTrace();
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
