/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vue;

/**
 *
 * @author Clarence
 */
public class Bookavol extends javax.swing.JInternalFrame {

    /**
     * Creates new form Bookavol
     */
    public Bookavol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paris = new javax.swing.JButton();
        berlin = new javax.swing.JButton();
        tokyo = new javax.swing.JButton();
        Mexico = new javax.swing.JButton();

        paris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/paris.png"))); // NOI18N

        berlin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/berlin.png"))); // NOI18N
        berlin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berlinActionPerformed(evt);
            }
        });

        tokyo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/tokyo.png"))); // NOI18N
        tokyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokyoActionPerformed(evt);
            }
        });

        Mexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/mexico.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mexico, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(berlin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tokyo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paris, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(915, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(paris, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(berlin)
                .addGap(31, 31, 31)
                .addComponent(tokyo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Mexico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(230, 230, 230))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tokyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokyoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokyoActionPerformed

    private void berlinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berlinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_berlinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mexico;
    private javax.swing.JButton berlin;
    private javax.swing.JButton paris;
    private javax.swing.JButton tokyo;
    // End of variables declaration//GEN-END:variables
}
