/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author Clarence
 */
//interfaclients == frame reserv==internalframe paiement == internalframe
public class Interfaceutili extends javax.swing.JPanel {

    /**
     * Creates new form Interfaceutili
     */
    public Interfaceutili() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopclients = new javax.swing.JDesktopPane();
        ajoutreserv = new javax.swing.JButton();
        newvol = new javax.swing.JButton();

        javax.swing.GroupLayout desktopclientsLayout = new javax.swing.GroupLayout(desktopclients);
        desktopclients.setLayout(desktopclientsLayout);
        desktopclientsLayout.setHorizontalGroup(
            desktopclientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        desktopclientsLayout.setVerticalGroup(
            desktopclientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        ajoutreserv.setBackground(new java.awt.Color(255, 255, 255));
        ajoutreserv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ajoutreserv.setForeground(new java.awt.Color(0, 204, 204));
        ajoutreserv.setText("Gérer vos réservations ");
        ajoutreserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutreservActionPerformed(evt);
            }
        });

        newvol.setBackground(new java.awt.Color(204, 204, 204));
        newvol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newvol.setForeground(new java.awt.Color(255, 153, 153));
        newvol.setText("Réserver un nouveau vol");
        newvol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newvolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newvol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajoutreserv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addComponent(desktopclients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajoutreserv)
                        .addGap(34, 34, 34)
                        .addComponent(newvol))
                    .addComponent(desktopclients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutreservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutreservActionPerformed
        desktopclients.removeAll();
        Reservation fr1 = new Reservation();
        desktopclients.add(fr1);
        desktopclients.setVisible(true); 
    }//GEN-LAST:event_ajoutreservActionPerformed

    private void newvolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newvolActionPerformed
        desktopclients.removeAll();
        Ajoutvol fvol = new Ajoutvol();
        desktopclients.add(fvol);
        desktopclients.setVisible(true);
    }//GEN-LAST:event_newvolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutreserv;
    private javax.swing.JDesktopPane desktopclients;
    private javax.swing.JButton newvol;
    // End of variables declaration//GEN-END:variables
}
