/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package modelmvc;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import DAO.*;
import controlmvc.EmailVerif;
import java.awt.event.KeyEvent;
import javax.swing.JDesktopPane;
import modelmvc.Connection;

/**
 *
 * @author Clarence
 */
public class CreaEmployes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employes
     */
    public CreaEmployes() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backg = new javax.swing.JPanel();
        infos = new javax.swing.JLabel();
        ground = new javax.swing.JPanel();
        reforeign = new javax.swing.JLabel();
        reftxt = new javax.swing.JTextField();
        namemploye = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        premployes = new javax.swing.JLabel();
        surnametxt = new javax.swing.JTextField();
        departement = new javax.swing.JLabel();
        depttxt = new javax.swing.JTextField();
        compagnie = new javax.swing.JLabel();
        compatxt = new javax.swing.JTextField();
        executer = new javax.swing.JButton();
        suppBouton = new javax.swing.JButton();
        ref2 = new javax.swing.JLabel();
        foreigntxt = new javax.swing.JTextField();
        executer2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        backg1 = new javax.swing.JPanel();
        infos1 = new javax.swing.JLabel();
        ground1 = new javax.swing.JPanel();
        ref1 = new javax.swing.JLabel();
        reftxt1 = new javax.swing.JTextField();
        namemploye1 = new javax.swing.JLabel();
        nametxt1 = new javax.swing.JTextField();
        premployes1 = new javax.swing.JLabel();
        surnametxt1 = new javax.swing.JTextField();
        departement1 = new javax.swing.JLabel();
        depttxt1 = new javax.swing.JTextField();
        compagnie1 = new javax.swing.JLabel();
        compatxt1 = new javax.swing.JTextField();
        executer1 = new javax.swing.JButton();
        suppBouton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des employes");

        backg.setBackground(new java.awt.Color(0, 153, 153));

        infos.setBackground(new java.awt.Color(255, 255, 255));
        infos.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        infos.setForeground(new java.awt.Color(255, 255, 255));
        infos.setText(" Informations employés");

        ground.setBackground(new java.awt.Color(204, 204, 204));

        reforeign.setBackground(new java.awt.Color(255, 255, 255));
        reforeign.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reforeign.setForeground(new java.awt.Color(255, 255, 255));
        reforeign.setText("Foreign");

        reftxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reftxtActionPerformed(evt);
            }
        });
        reftxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reftxtKeyTyped(evt);
            }
        });

        namemploye.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        namemploye.setForeground(new java.awt.Color(255, 255, 255));
        namemploye.setText("Nom");

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        premployes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        premployes.setForeground(new java.awt.Color(255, 255, 255));
        premployes.setText("Prénom");

        surnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnametxtActionPerformed(evt);
            }
        });

        departement.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        departement.setForeground(new java.awt.Color(255, 255, 255));
        departement.setText("Département");

        depttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depttxtActionPerformed(evt);
            }
        });

        compagnie.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        compagnie.setForeground(new java.awt.Color(255, 255, 255));
        compagnie.setText("Compagnie");

        compatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compatxtActionPerformed(evt);
            }
        });

        executer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        executer.setForeground(new java.awt.Color(0, 153, 153));
        executer.setText("Exécuter");
        executer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executerActionPerformed(evt);
            }
        });

        suppBouton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        suppBouton.setForeground(new java.awt.Color(153, 0, 51));
        suppBouton.setText("Supprimer");
        suppBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppBoutonActionPerformed(evt);
            }
        });

        ref2.setBackground(new java.awt.Color(255, 255, 255));
        ref2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ref2.setForeground(new java.awt.Color(255, 255, 255));
        ref2.setText("Référence");

        foreigntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                foreigntxtKeyTyped(evt);
            }
        });

        executer2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        executer2.setForeground(new java.awt.Color(102, 0, 255));
        executer2.setText("Update");
        executer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groundLayout = new javax.swing.GroupLayout(ground);
        ground.setLayout(groundLayout);
        groundLayout.setHorizontalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundLayout.createSequentialGroup()
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ref2)
                            .addGroup(groundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namemploye, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(premployes))))
                        .addGap(86, 86, 86)
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(groundLayout.createSequentialGroup()
                                .addComponent(compagnie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(compatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(groundLayout.createSequentialGroup()
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departement)
                                    .addComponent(reforeign))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foreigntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(suppBouton)
                        .addGap(40, 40, 40)
                        .addComponent(executer2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(executer, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        groundLayout.setVerticalGroup(
            groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groundLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reforeign)
                    .addComponent(foreigntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ref2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groundLayout.createSequentialGroup()
                        .addComponent(depttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(compatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groundLayout.createSequentialGroup()
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namemploye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nametxt))
                            .addComponent(departement))
                        .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groundLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(compagnie)))
                            .addGroup(groundLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(premployes)))))
                .addGap(72, 72, 72)
                .addGroup(groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(executer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(executer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppBouton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout backgLayout = new javax.swing.GroupLayout(backg);
        backg.setLayout(backgLayout);
        backgLayout.setHorizontalGroup(
            backgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(backgLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(infos, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgLayout.setVerticalGroup(
            backgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(infos)
                .addGap(18, 18, 18)
                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Gestion des employes");

        backg1.setBackground(new java.awt.Color(0, 153, 153));

        infos1.setBackground(new java.awt.Color(255, 255, 255));
        infos1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        infos1.setForeground(new java.awt.Color(255, 255, 255));
        infos1.setText(" Informations employés");

        ground1.setBackground(new java.awt.Color(204, 204, 204));

        ref1.setBackground(new java.awt.Color(255, 255, 255));
        ref1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ref1.setForeground(new java.awt.Color(255, 255, 255));
        ref1.setText("Référence");

        reftxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reftxt1ActionPerformed(evt);
            }
        });

        namemploye1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        namemploye1.setForeground(new java.awt.Color(255, 255, 255));
        namemploye1.setText("Nom");

        nametxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxt1ActionPerformed(evt);
            }
        });

        premployes1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        premployes1.setForeground(new java.awt.Color(255, 255, 255));
        premployes1.setText("Prénom");

        surnametxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnametxt1ActionPerformed(evt);
            }
        });

        departement1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        departement1.setForeground(new java.awt.Color(255, 255, 255));
        departement1.setText("Département");

        depttxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depttxt1ActionPerformed(evt);
            }
        });

        compagnie1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        compagnie1.setForeground(new java.awt.Color(255, 255, 255));
        compagnie1.setText("Compagnie");

        compatxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compatxt1ActionPerformed(evt);
            }
        });

        executer1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        executer1.setForeground(new java.awt.Color(0, 153, 153));
        executer1.setText("Exécuter");
        executer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executer1ActionPerformed(evt);
            }
        });

        suppBouton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        suppBouton1.setForeground(new java.awt.Color(153, 0, 51));
        suppBouton1.setText("Supprimer");
        suppBouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppBouton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ground1Layout = new javax.swing.GroupLayout(ground1);
        ground1.setLayout(ground1Layout);
        ground1Layout.setHorizontalGroup(
            ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ground1Layout.createSequentialGroup()
                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ground1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ground1Layout.createSequentialGroup()
                                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(namemploye1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(premployes1))
                                    .addComponent(ref1))
                                .addGap(74, 74, 74)
                                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(surnametxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                    .addComponent(reftxt1)
                                    .addComponent(nametxt1)))
                            .addGroup(ground1Layout.createSequentialGroup()
                                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departement1)
                                    .addComponent(compagnie1))
                                .addGap(18, 18, 18)
                                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suppBouton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(depttxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                        .addComponent(compatxt1))))))
                    .addGroup(ground1Layout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(executer1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(639, Short.MAX_VALUE))
        );
        ground1Layout.setVerticalGroup(
            ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ref1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reftxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namemploye1)
                    .addComponent(nametxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(premployes1)
                    .addGroup(ground1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(surnametxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departement1)
                    .addComponent(depttxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compagnie1)
                    .addComponent(compatxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(executer1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(suppBouton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout backg1Layout = new javax.swing.GroupLayout(backg1);
        backg1.setLayout(backg1Layout);
        backg1Layout.setHorizontalGroup(
            backg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backg1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(infos1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backg1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        backg1Layout.setVerticalGroup(
            backg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backg1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(infos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 653, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 653, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 385, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 385, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depttxtActionPerformed

    private void executerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executerActionPerformed
        // TODO add your handling code here:
        Employe employe = new Employe();
        EmployeDAOImpl employedao = new EmployeDAOImpl();

        employe.SetId(Integer.parseInt(reftxt.getText()));
        employe.SetNom(nametxt.getText());
        employe.SetPrenom(surnametxt.getText());
        employe.SetCompagnie(compatxt.getText());
        employe.SetDepartement(depttxt.getText());
        employe.SetForeignKey(Integer.parseInt(foreigntxt.getText()));

        employedao.AddEmploye(employe);
        setVisible(false);
        Connection.affiche("Employé créé !");
    }//GEN-LAST:event_executerActionPerformed

    private void surnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnametxtActionPerformed

    private void reftxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reftxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reftxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void compatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compatxtActionPerformed

    private void suppBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppBoutonActionPerformed
        // TODO add your handling code here:
        Employe employe = new Employe();
        EmployeDAOImpl employedao = new EmployeDAOImpl();

        employe.SetId(Integer.parseInt(reftxt.getText()));
        employe.SetNom(nametxt.getText());
        employe.SetPrenom(surnametxt.getText());
        employe.SetCompagnie(compatxt.getText());
        employe.SetDepartement(depttxt.getText());
        employe.SetForeignKey(Integer.parseInt(foreigntxt.getText()));

        employedao.DeleteEmploye(employe.GetId());
        setVisible(false);
        Connection.affiche("Employé supprimé !");

    }//GEN-LAST:event_suppBoutonActionPerformed

    private void reftxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reftxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reftxt1ActionPerformed

    private void nametxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxt1ActionPerformed

    private void surnametxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnametxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnametxt1ActionPerformed

    private void depttxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depttxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depttxt1ActionPerformed

    private void compatxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compatxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compatxt1ActionPerformed

    private void executer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_executer1ActionPerformed

    private void suppBouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppBouton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppBouton1ActionPerformed

    private void executer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executer2ActionPerformed
        // TODO add your handling code here:
        Employe employe = new Employe();
        EmployeDAOImpl employedao = new EmployeDAOImpl();

        employe.SetId(Integer.parseInt(reftxt.getText()));
        employe.SetNom(nametxt.getText());
        employe.SetPrenom(surnametxt.getText());
        employe.SetCompagnie(compatxt.getText());
        employe.SetDepartement(depttxt.getText());
        employe.SetForeignKey(Integer.parseInt(foreigntxt.getText()));

        employedao.UpdateEmploye(employe.GetId(),employe);
        setVisible(false);
        Connection.affiche("Employé mis à jour!");
    }//GEN-LAST:event_executer2ActionPerformed

    private void reftxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reftxtKeyTyped
        char r = evt.getKeyChar();
            if ( ((r < '0') || (r > '9')) && (r != KeyEvent.VK_BACK_SPACE)) {
                  evt.consume();  // ignorer l'événement
             }
    }//GEN-LAST:event_reftxtKeyTyped

    private void foreigntxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foreigntxtKeyTyped
        char foreign = evt.getKeyChar();
            if ( ((foreign < '0') || (foreign > '9')) && (foreign != KeyEvent.VK_BACK_SPACE)) {
                  evt.consume();  // ignorer l'événement
             }
    }//GEN-LAST:event_foreigntxtKeyTyped

    public void run() {
        new CreaEmployes().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backg;
    private javax.swing.JPanel backg1;
    private javax.swing.JLabel compagnie;
    private javax.swing.JLabel compagnie1;
    private javax.swing.JTextField compatxt;
    private javax.swing.JTextField compatxt1;
    private javax.swing.JLabel departement;
    private javax.swing.JLabel departement1;
    private javax.swing.JTextField depttxt;
    private javax.swing.JTextField depttxt1;
    private javax.swing.JButton executer;
    private javax.swing.JButton executer1;
    private javax.swing.JButton executer2;
    private javax.swing.JTextField foreigntxt;
    private javax.swing.JPanel ground;
    private javax.swing.JPanel ground1;
    private javax.swing.JLabel infos;
    private javax.swing.JLabel infos1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel namemploye;
    private javax.swing.JLabel namemploye1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField nametxt1;
    private javax.swing.JLabel premployes;
    private javax.swing.JLabel premployes1;
    private javax.swing.JLabel ref1;
    private javax.swing.JLabel ref2;
    private javax.swing.JLabel reforeign;
    private javax.swing.JTextField reftxt;
    private javax.swing.JTextField reftxt1;
    private javax.swing.JButton suppBouton;
    private javax.swing.JButton suppBouton1;
    private javax.swing.JTextField surnametxt;
    private javax.swing.JTextField surnametxt1;
    // End of variables declaration//GEN-END:variables
}
